In [3]:

new = 2 - 0.1 * (4*2 + 4)
new 

0.7999999999999998

In [12]:
w = [0,1] 
X = [[1,1],[1,3],[1,5],[1,4],[1,2]]
y = [2,4,5,3,3]

In [13]:
import numpy as np
np.sum((np.dot(X,w) - y)**2)/5

0.8

In [83]:
w = [2,-1,4,8]
X = [1,5,1,2]
y = 6

In [15]:
w=w-0.01*np.dot((np.dot(X,w)-y),X)
w

array([ 1.89, -1.55,  3.89,  7.78])

In [16]:
w = [2,-1,10,8]
X = [1,5,1,2]
y = 10
eta = 0.1
alpha = 0.3

In [17]:
w = w - eta * (np.dot((np.dot(X,w)-y),X) + np.append(0,alpha*np.sign(w[1:]))) 
w

array([ 0.7 , -7.47,  8.67,  5.37])

In [18]:
(1/3)*(1/3)*(1/3)*(1/3)*(1/3)*(1/4)

0.0010288065843621398

In [23]:
((5+1)/(8+6))*((5+1)/(8+6))*((5+1)/(8+6))*((0+1)/(8+6))*((0+1)/(8+6))

0.0004016183732968405

In [70]:
W = np.transpose(np.array([[1., 1.], 
              [-4., 3.], 
              [-1., -3.]])).reshape(2, 3)
b = np.array([[-2.], 
              [-11.], 
              [-1.]])
x = np.array([0., 1.])

In [67]:
np.dot(x,W)

array([ 1.,  3., -3.])

In [71]:
def scores(W, b, x):
    return np.dot(x, W) + b

def probas(W, b, x):
    sc = scores(W, b, x)
    sc_exp = np.exp(sc)
    return sc_exp / np.sum(sc_exp)

In [73]:
np.round(probas(W, b, x), 3)

array([[0.032, 0.236, 0.001],
       [0.   , 0.   , 0.   ],
       [0.087, 0.642, 0.002]])

In [82]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

params = {'lr__C': [1.0, 10.0, 100.0] }
 
lr_pipeline = Pipeline([('scaler', StandardScaler()),
                        ('lr', LogisticRegression(penalty = 'l1'))])

gs = GridSearchCV(lr_pipeline, param_grid=params, cv=5, refit=True)
gs.fit(X_train, y_train)
y_preds = gs.predict(X_test)
score =accuracy_score(y_test, y_preds)
print(score)

1.0
